#!/bin/sh
#
# nginx - this script starts and stops the nginx daemon
#
# chkconfig:   - 85 15
# description:  NGINX is an HTTP(S) server, HTTP(S) reverse \
#               proxy and IMAP/POP3 proxy server
# processname: nginx

# Source function library.
. /etc/init.d/functions
 
[ -f /etc/init.d/nginxstart.sh ] || exit 0
[ -f /etc/init.d/nginxstop.sh ] || exit 0
 
RETVAL=0
 
umask 077
 
start() {
       echo -n $"Starting Nginx: "
       sh /etc/init.d/nginxstart.sh
       echo
       return $RETVAL
}
stop() {
       echo -n $"Shutting down Nginx: "
	   sh /etc/init.d/nginxstop.sh
       echo
       return $RETVAL
}
restart() {
       stop
       start
}
case "$1" in
start)
       start
       ;;
stop)
       stop
       ;;
restart|reload)
       restart
       ;;
*)
       echo $"Usage: $0 {start|stop|restart}"
       exit 1
esac
 
exit $?